<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Cari di YoRipe_header-yoripe-logo</name>
   <tag></tag>
   <elementGuidId>29cbacb7-a2a6-45a3-9946-89779c6934b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.header-yoripe-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari di YoRipe'])[1]/preceding::*[name()='svg'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>929abb0e-93b8-426c-9a57-8f20f5061425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>67ed12d8-35b7-46ae-a1ce-c5dbc1542745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>4bef95d8-2cfa-4837-94cd-645445677528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 100 35</value>
      <webElementGuid>e2957096-837d-4a56-a5cf-1144ef8cc9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>017caddb-72e8-4512-96eb-40c75f293838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>b3853805-ac76-44d5-a5d0-6d9bff3b69e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-yoripe-logo</value>
      <webElementGuid>6a8e5799-e38a-4e4f-b207-2bbefb00431c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;position-relative root-inner-wrapper&quot;]/div[@class=&quot;topbar-wrapper-container&quot;]/div[@class=&quot;topbar-container&quot;]/div[@class=&quot;topbar-wrappper&quot;]/div[@class=&quot;topbar-container-header&quot;]/div[@class=&quot;header-more-wrapper&quot;]/a[@class=&quot;no-link header-icon-container&quot;]/svg[@class=&quot;header-yoripe-logo&quot;]</value>
      <webElementGuid>3a59bafd-62ef-47b2-b612-54ce4867a33a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari di YoRipe'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>fbf3e19b-e49c-4729-984a-d4b30cd8375d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>b38192dc-a03f-40de-9178-279feee889d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
