<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LIVE</name>
   <tag></tag>
   <elementGuidId>13401180-15c6-400d-a403-7570c6d6a893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>15d155b0-591f-4dd5-a33b-3399a382845b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>prev</value>
      <webElementGuid>5cbc5250-d57e-4477-ad9e-d184a54a1e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-link header-nav</value>
      <webElementGuid>c2df0869-a5f9-42d2-93e6-276481c4f555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/livestreams</value>
      <webElementGuid>af06773e-1d89-4a75-a535-38b4c479240a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LIVE</value>
      <webElementGuid>499a8f03-44cc-47fa-ba95-d18136677458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;position-relative root-inner-wrapper&quot;]/div[@class=&quot;topbar-wrapper-container&quot;]/div[@class=&quot;topbar-container&quot;]/div[@class=&quot;web-only&quot;]/div[@class=&quot;topbar-container-tabs&quot;]/div[@class=&quot;invis-scroll header-nav-wrapper&quot;]/div[@class=&quot;header-nav-container&quot;]/a[@class=&quot;no-link header-nav&quot;]</value>
      <webElementGuid>b2f53c2e-ef7c-45f5-8c4c-eb504b29ec26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div/div[3]/a</value>
      <webElementGuid>c46d1efe-cad0-489c-97b3-8efc3692aa3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resep'])[1]/following::a[1]</value>
      <webElementGuid>59a97a11-d8b6-4444-8f06-dc10fccace1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/following::a[2]</value>
      <webElementGuid>bce882f0-fd27-4b6d-8dd5-5961b0db8b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tantangan Seru'])[1]/preceding::a[1]</value>
      <webElementGuid>ae31c340-c031-476b-8005-a96d74558f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/livestreams')]</value>
      <webElementGuid>3bf300d9-330a-408a-b7b3-e8507d1f6747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/a</value>
      <webElementGuid>2c94dfb5-1246-4632-8145-80b146861152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/livestreams' and (text() = 'LIVE' or . = 'LIVE')]</value>
      <webElementGuid>64a0f53e-6147-4f8a-a9c9-0851361bf94e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
